apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  volumeName: task-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi